### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Vrekt** [Vrekt/FortniteXMPP2#3]
- [x] Fix fake parties - Currently broken for 8.3

- [ ] Create a object for each party type and support all fields

- [x] Only use hex for sessions, ids, etc.

- [x] Support raw squad assignment data

- [ ] Try to find tournament completed payload again and support it

- [ ] Update wiki
